from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "04_data_extraction"
OUT_DIR.mkdir(exist_ok=True)


rows = [
    {
        "study_id": "ULTIMA_2014",
        "short_name": "ULTIMA",
        "node": "USCDT",
        "arm_label": "USAT/USCDT + UFH",
        "n": 30,
        "baseline_mean": 1.28,
        "baseline_sd": 0.19,
        "early_timepoint": "24h",
        "early_followup_mean": 0.99,
        "early_followup_sd": 0.17,
        "early_change_reduction_mean": 0.30,
        "early_change_reduction_sd": 0.20,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "echocardiographic RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Mean RV/LV ratio from 1.28+/-0.19 to 0.99+/-0.17 at 24h; mean decrease 0.30+/-0.20.",
    },
    {
        "study_id": "ULTIMA_2014",
        "short_name": "ULTIMA",
        "node": "AC",
        "arm_label": "UFH alone",
        "n": 29,
        "baseline_mean": 1.20,
        "baseline_sd": 0.14,
        "early_timepoint": "24h",
        "early_followup_mean": 1.17,
        "early_followup_sd": 0.20,
        "early_change_reduction_mean": 0.03,
        "early_change_reduction_sd": 0.16,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "echocardiographic RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Mean RV/LV ratio from 1.20+/-0.14 to 1.17+/-0.20 at 24h; mean decrease 0.03+/-0.16.",
    },
    {
        "study_id": "SUNSET_sPE_2021",
        "short_name": "SUNSET sPE",
        "node": "USCDT",
        "arm_label": "USAT/EKOS",
        "n": 40,
        "baseline_mean": 1.50,
        "baseline_sd": 0.30,
        "early_timepoint": "48h",
        "early_followup_mean": 1.20,
        "early_followup_sd": 0.20,
        "early_change_reduction_mean": 0.35,
        "early_change_reduction_sd": 0.34,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "RV/LV 1.5+/-0.3 to 1.2+/-0.2 at 48h; delta 0.35+/-0.34.",
    },
    {
        "study_id": "SUNSET_sPE_2021",
        "short_name": "SUNSET sPE",
        "node": "CDT",
        "arm_label": "Standard CDT",
        "n": 41,
        "baseline_mean": 1.70,
        "baseline_sd": 0.40,
        "early_timepoint": "48h",
        "early_followup_mean": 1.10,
        "early_followup_sd": 0.20,
        "early_change_reduction_mean": 0.59,
        "early_change_reduction_sd": 0.42,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "RV/LV 1.7+/-0.4 to 1.1+/-0.2 at 48h; delta 0.59+/-0.42.",
    },
    {
        "study_id": "PEERLESS_2025",
        "short_name": "PEERLESS",
        "node": "LBAT",
        "arm_label": "FlowTriever LBMT",
        "n": 274,
        "baseline_mean": "",
        "baseline_sd": "",
        "early_timepoint": "24h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.32,
        "early_change_reduction_sd": 0.24,
        "long_term_timepoint": "",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio reduction",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Mean RV/LV reduction 0.32+/-0.24 at 24h.",
    },
    {
        "study_id": "PEERLESS_2025",
        "short_name": "PEERLESS",
        "node": "CDT",
        "arm_label": "CDT mixed",
        "n": 276,
        "baseline_mean": "",
        "baseline_sd": "",
        "early_timepoint": "24h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.30,
        "early_change_reduction_sd": 0.26,
        "long_term_timepoint": "",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio reduction",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Mean RV/LV reduction 0.30+/-0.26 at 24h; CDT arm is mixed CDT/USCDT.",
    },
    {
        "study_id": "STORM_PE_2025",
        "short_name": "STORM-PE",
        "node": "CAT",
        "arm_label": "CAVT/Penumbra + AC",
        "n": 47,
        "baseline_mean": 1.63,
        "baseline_sd": 0.36,
        "early_timepoint": "48h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.52,
        "early_change_reduction_sd": 0.37,
        "long_term_timepoint": "90d planned",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio reduction",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Baseline 1.63+/-0.36; 48h RV/LV reduction 0.52+/-0.37.",
    },
    {
        "study_id": "STORM_PE_2025",
        "short_name": "STORM-PE",
        "node": "AC",
        "arm_label": "AC alone",
        "n": 53,
        "baseline_mean": 1.56,
        "baseline_sd": 0.35,
        "early_timepoint": "48h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.24,
        "early_change_reduction_sd": 0.40,
        "long_term_timepoint": "90d planned",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio reduction",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "Baseline 1.56+/-0.35; 48h RV/LV reduction 0.24+/-0.40.",
    },
    {
        "study_id": "ZHANG_2018",
        "short_name": "Zhang 2018",
        "node": "ST",
        "arm_label": "Low-dose rt-PA + LMWH",
        "n": 33,
        "baseline_mean": 1.26,
        "baseline_sd": 0.22,
        "early_timepoint": "24h",
        "early_followup_mean": 0.96,
        "early_followup_sd": 0.18,
        "early_change_reduction_mean": 0.31,
        "early_change_reduction_sd": 0.18,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "CT RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "RV/LV from 1.26+/-0.22 to 0.96+/-0.18 at 24h; mean difference 0.31+/-0.18.",
    },
    {
        "study_id": "ZHANG_2018",
        "short_name": "Zhang 2018",
        "node": "AC",
        "arm_label": "LMWH",
        "n": 33,
        "baseline_mean": 1.22,
        "baseline_sd": 0.19,
        "early_timepoint": "24h",
        "early_followup_mean": 1.17,
        "early_followup_sd": 0.21,
        "early_change_reduction_mean": 0.04,
        "early_change_reduction_sd": 0.16,
        "long_term_timepoint": "90d",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "CT RV/LV ratio",
        "analysis_status": "main_continuous_nma",
        "conversion_needed": "no",
        "source_note": "RV/LV from 1.22+/-0.19 to 1.17+/-0.21 at 24h; mean difference 0.04+/-0.16.",
    },
    {
        "study_id": "PRETHA_2026",
        "short_name": "PRETHA",
        "node": "CAT",
        "arm_label": "Penumbra Indigo CAT8 thrombectomy",
        "n": 13,
        "baseline_mean": 1.20,
        "baseline_sd": "",
        "early_timepoint": "48h",
        "early_followup_mean": 0.89,
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.30,
        "early_change_reduction_sd": "",
        "long_term_timepoint": "1/6/12mo",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio",
        "analysis_status": "not_main_missing_sd",
        "conversion_needed": "yes_missing_sd",
        "source_note": "RV/LV 1.2 to 0.89 at 48h; mean decrease 0.3; SD not available in v0.2.",
    },
    {
        "study_id": "PRETHA_2026",
        "short_name": "PRETHA",
        "node": "CDT",
        "arm_label": "Trans-catheter thrombolysis",
        "n": 13,
        "baseline_mean": 1.27,
        "baseline_sd": "",
        "early_timepoint": "48h",
        "early_followup_mean": 0.88,
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.40,
        "early_change_reduction_sd": "",
        "long_term_timepoint": "1/6/12mo",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio",
        "analysis_status": "not_main_missing_sd",
        "conversion_needed": "yes_missing_sd",
        "source_note": "RV/LV 1.27 to 0.88 at 48h; mean decrease 0.4; SD not available in v0.2.",
    },
    {
        "study_id": "PRETHA_2026",
        "short_name": "PRETHA",
        "node": "AC",
        "arm_label": "Conservative treatment",
        "n": 13,
        "baseline_mean": 1.23,
        "baseline_sd": "",
        "early_timepoint": "48h",
        "early_followup_mean": 1.12,
        "early_followup_sd": "",
        "early_change_reduction_mean": 0.11,
        "early_change_reduction_sd": "",
        "long_term_timepoint": "1/6/12mo",
        "long_term_value": "",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV ratio",
        "analysis_status": "not_main_missing_sd",
        "conversion_needed": "yes_missing_sd",
        "source_note": "RV/LV 1.23 to 1.12 at 48h; SD not available in v0.2.",
    },
    {
        "study_id": "SINHA_2017",
        "short_name": "Sinha 2017",
        "node": "ST",
        "arm_label": "Tenecteplase + UFH",
        "n": 45,
        "baseline_mean": 1.14,
        "baseline_sd": 0.11,
        "early_timepoint": "unclear",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": "",
        "early_change_reduction_sd": "",
        "long_term_timepoint": "30d",
        "long_term_value": "RV function improvement 31/45",
        "rv_recovery_event_n": 31,
        "rv_recovery_total_n": 45,
        "measure": "baseline RV/LV; RV function improvement",
        "analysis_status": "long_term_binary_or_pending_continuous",
        "conversion_needed": "yes_no_followup_mean_sd",
        "source_note": "Baseline RV/LV 1.14+/-0.11; RV function improvement 31/45.",
    },
    {
        "study_id": "SINHA_2017",
        "short_name": "Sinha 2017",
        "node": "AC",
        "arm_label": "Placebo + UFH",
        "n": 41,
        "baseline_mean": 1.16,
        "baseline_sd": 0.14,
        "early_timepoint": "unclear",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": "",
        "early_change_reduction_sd": "",
        "long_term_timepoint": "30d",
        "long_term_value": "RV function improvement 16/41",
        "rv_recovery_event_n": 16,
        "rv_recovery_total_n": 41,
        "measure": "baseline RV/LV; RV function improvement",
        "analysis_status": "long_term_binary_or_pending_continuous",
        "conversion_needed": "yes_no_followup_mean_sd",
        "source_note": "Baseline RV/LV 1.16+/-0.14; RV function improvement 16/41.",
    },
    {
        "study_id": "CANARY_2022",
        "short_name": "CANARY",
        "node": "CDT",
        "arm_label": "cCDT + anticoagulation",
        "n": 48,
        "baseline_mean": "",
        "baseline_sd": "",
        "early_timepoint": "72h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": "",
        "early_change_reduction_sd": "",
        "long_term_timepoint": "3mo",
        "long_term_value": "RV/LV>0.9: 13/48 at 72h; 2/46 at 3mo; unrecovered RV 3/46",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV >0.9 or unrecovered RV",
        "analysis_status": "binary_rv_recovery_not_continuous",
        "conversion_needed": "yes_binary_endpoint",
        "source_note": "CANARY reports RV/LV>0.9 and unrecovered RV proportions, not mean/SD change in v0.2.",
    },
    {
        "study_id": "CANARY_2022",
        "short_name": "CANARY",
        "node": "AC",
        "arm_label": "Anticoagulation",
        "n": 46,
        "baseline_mean": "",
        "baseline_sd": "",
        "early_timepoint": "72h",
        "early_followup_mean": "",
        "early_followup_sd": "",
        "early_change_reduction_mean": "",
        "early_change_reduction_sd": "",
        "long_term_timepoint": "3mo",
        "long_term_value": "RV/LV>0.9: 24/46 at 72h; 5/39 at 3mo; unrecovered RV 11/39",
        "rv_recovery_event_n": "",
        "rv_recovery_total_n": "",
        "measure": "RV/LV >0.9 or unrecovered RV",
        "analysis_status": "binary_rv_recovery_not_continuous",
        "conversion_needed": "yes_binary_endpoint",
        "source_note": "CANARY reports RV/LV>0.9 and unrecovered RV proportions, not mean/SD change in v0.2.",
    },
]


df = pd.DataFrame(rows)

csv_path = OUT_DIR / "RV_LV_data_v0.1.csv"
xlsx_path = OUT_DIR / "RV_LV_data_v0.1.xlsx"
md_path = OUT_DIR / "RV_LV_data_v0.1.md"

df.to_csv(csv_path, index=False, encoding="utf-8-sig")
with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="RV_LV_Arm_Level_v0.1", index=False)
    summary = (
        df.groupby(["analysis_status", "conversion_needed"], dropna=False)
        .size()
        .reset_index(name="arms")
    )
    summary.to_excel(writer, sheet_name="Summary", index=False)
    dictionary = pd.DataFrame(
        [
            ["early_change_reduction_mean", "Positive values mean greater RV/LV reduction or improvement."],
            ["analysis_status=main_continuous_nma", "Has n, mean change/reduction, and SD for early 24-48h continuous NMA."],
            ["not_main_missing_sd", "Mean available but SD unavailable; do not enter main continuous NMA until converted or recovered."],
            ["long_term_binary_or_pending_continuous", "Long-term/binary RV recovery data; not part of early continuous NMA."],
            ["binary_rv_recovery_not_continuous", "Only binary RV recovery/persistent RV dysfunction data available."],
        ],
        columns=["field_or_code", "meaning"],
    )
    dictionary.to_excel(writer, sheet_name="Data_Dictionary", index=False)

with md_path.open("w", encoding="utf-8") as f:
    f.write("# RV/LV Data v0.1\n\n")
    f.write("Primary early timepoint is 24-48h. Positive change means greater RV/LV reduction/improvement.\n\n")
    f.write("```csv\n")
    f.write(df.to_csv(index=False))
    f.write("```\n")
    f.write("\n")

print(f"Wrote {csv_path}")
print(f"Wrote {xlsx_path}")
print(f"Wrote {md_path}")
print(df["analysis_status"].value_counts().to_string())
